version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: darkweb_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: darkweb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - darkweb_net

    restart: always

  tor:
    image: osminogin/tor-simple
    container_name: darkweb_tor
    ports:
      - "9050:9050"
    networks:
      - darkweb_net
    restart: always

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: darkweb_scraper
    depends_on:
      - db
      - tor
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: darkweb
      DB_PORT: 5432
      TOR_PROXY: "socks5://tor:9050"
    networks:
      - darkweb_net
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: darkweb_panel
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: darkweb
      DB_PORT: 5432
    networks:
      - darkweb_net
    restart: always

networks:
  darkweb_net:
    driver: bridge

volumes:
  postgres_data:
